name: PR Label Enforcement

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Labels
        uses: actions/github-script@v6
        with:
          script: |
            const requiredLabels = ['bug', 'feature', 'enhancement'];
            const pr = context.payload.pull_request;
            const prLabels = pr.labels.map(label => label.name);
            const hasRequiredLabel = requiredLabels.some(label => prLabels.includes(label));

            if (!hasRequiredLabel) {
              return {
                conclusion: 'failure',
                output: {
                  title: 'Missing Required Labels',
                  summary: `Your PR is missing required labels. Add at least one of the following:\n\n- **bug**\n- **feature**\n- **enhancement**`,
                  text: 'Labels help categorize the PR and ensure proper tracking.'
                },
              };
            }

            return {
              conclusion: 'success',
              output: {
                title: 'Label Check Passed',
                summary: 'Your PR has at least one required label.',
              },
            };
