name: Enforce PR Labels

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
jobs:
  enforce-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Labels
        uses: actions/github-script@v6
        with:
          script: |
            const requiredLabels = [
              'bug', 
              'enhancement', 
              'infrastructure', 
              'documentation', 
              'technical debt',
              'release', 
              'dependencies'
            ];

            const pr = context.payload.pull_request;
            const prLabels = pr.labels.map(label => label.name);

            // Check if the PR has at least one required label
            const hasRequiredLabel = requiredLabels.some(label => prLabels.includes(label));

            if (!hasRequiredLabel) {
              return {
                conclusion: 'failure',
                output: {
                  title: 'Missing Required Labels',
                  summary: `Your PR must have at least one of the following labels:\n\n` +
                           `- **bug**\n` +
                           `- **enhancement**\n` +
                           `- **infrastructure**\n` +
                           `- **documentation**\n` +
                           `- **technical debt**\n` +
                           `- **release**\n` +
                           `- **dependencies**`,
                  text: ``
                },
              };
            }

            return {
              conclusion: 'success',
              output: {
                title: 'PR Label Check Passed',
                summary: 'Your PR contains a valid label.'
              }
            };
